export enum Message {
  Approval = "Approval Voting",
  BallotFormat = "Format",
  Ballots = "Ballots:",
  BordaCount = "Borda Count",
  Breezi = "Breezi",
  Copied = "Copied!",
  Copy = "Copy",
  Divider = "——————————————————————",
  Loading = "Loading...",
  Hr = "--------------------------------------------------------------------------------------------",
  NoResults = "(no results found)",
  Preferences = "Preferences:",
  RankedPairs = "Ranked Pairs",
  RankedPoll = "Ranked-ballot poll",
  Rundown = "Rundown",
  SkipFirstPost = "Ignore first post",
  SkipLastPost = "Ignore last post",
  SlateType = "Slate type",
  SmithSet = "The top voting cycle is",
  Submit = "Submit",
  Tool = "Tool",
}
